version: '2'
services:
    finncars-app:
        image: finncars
        external_links:
            - finncars-cassandra:cassandra
            - kafka:kafka
            - zookeeper:zookeeper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8081:8080
    finncars-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: finncars-cassandra
    finncars-cassandra-node:
        image: cassandra:3.9
        links:
            - finncars-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    finncars-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: finncars-cassandra-migration
        links:
            - finncars-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
