version: '2'
services:
    finncars-cassandra:
        container_name: finncars-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/FinnCars/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    finncars-cassandra-node:
        image: cassandra:3.9
        links:
            - finncars-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    finncars-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: finncars-cassandra-migration
        links:
            - finncars-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
